name: Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - master

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        services:
          mongodb:
            image: prismagraphql/mongo-single-replica:4.4.3-bionic
            env:
              MONGO_INITDB_ROOT_USERNAME: tuanln
              MONGO_INITDB_ROOT_PASSWORD: Sieunhangaovippro12012010!
            ports:
              - 27017:27017
        env:
          DATABASE_URL: mongodb://localhost:27017/local

        steps:
            - uses: actions/checkout@v3

            - name: Install Vercel CLI
              run: npm install --global vercel
            - name: Install Prisma
              run: npx prisma generate
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
